version: '3.9'

services:
    app:
        build: .
        restart: always
        ports:
            - '3000:3000'
        depends_on: 
            - db
        links:
            - db
        command: npm start
    db:
        image: postgres
        restart: always
        volumes: 
            - './data:/var/lig/postgresql/data'
        ports:
            - '5432:5432'
        environment: 
            POSTGRES_USER: 'adminer'
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: 'api-cpf'
